In [6]:
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import math
import pandas as pd
import pickle
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import InputLayer, Input
from tensorflow.python.keras.layers import Reshape, MaxPooling2D
from tensorflow.python.keras.layers import Conv2D, Dense, Flatten

In [41]:
#emotion = {'Angry': 0, 'Disgust': 1, 'Fear': 2, 'Happy': 3,
#           'Sad': 4, 'Surprise': 5, 'Neutral': 6, 'Contempt':7}

In [57]:
with open('../imagelist.pkl', 'rb') as fin:
    kaggle_pkl = pickle.load(fin)

In [75]:
kaggle_pkl[0][0]

'Angry'

In [81]:
kaggle_img = [np.asarray(item[1]) for item in kaggle_pkl]
kaggle_img

[array([  70.,   80.,   82., ...,  106.,  109.,   82.]),
 array([ 151.,  150.,  147., ...,  193.,  183.,  184.]),
 array([ 231.,  212.,  156., ...,   88.,  110.,  152.]),
 array([  24.,   32.,   36., ...,  142.,  143.,  142.]),
 array([  4.,   0.,   0., ...,  30.,  29.,  30.]),
 array([ 55.,  55.,  55., ...,  34.,  30.,  57.]),
 array([  20.,   17.,   19., ...,   99.,  107.,  118.]),
 array([  77.,   78.,   79., ...,  125.,   67.,   68.]),
 array([ 85.,  84.,  90., ...,  58.,  73.,  84.]),
 array([ 255.,  254.,  255., ...,  254.,  255.,  255.]),
 array([  30.,   24.,   21., ...,  172.,  173.,  173.]),
 array([ 39.,  75.,  78., ...,  84.,  83.,  87.]),
 array([ 219.,  213.,  206., ...,    0.,    0.,    0.]),
 array([ 148.,  144.,  130., ...,  112.,  111.,  111.]),
 array([  4.,   2.,  13., ...,   3.,   7.,  12.]),
 array([ 107.,  107.,  109., ...,   83.,   84.,  106.]),
 array([ 14.,  14.,  18., ...,   9.,  10.,  10.]),
 array([ 255.,  255.,  255., ...,   79.,   79.,   83.]),
 array([ 1

In [45]:
#kaggle_img = [np.asarray(item[1]) for item in kaggle_pkl]
#kaggle_label = [np.asarray(item[0]) for item in kaggle_pkl]
#kaggle_label = pd.DataFrame(kaggle_label, columns = ['emotion'])
#kaggle_img = kaggle_pkl['pixels'].as_matrix()
#kaggle_label = kaggle_pkl['emotion']

In [84]:
temp_list = []
[temp_list.append(list(item)) for item in kaggle_img]
kaggle_img_train= np.array(temp_list)

In [86]:
kaggle_label = [np.asarray(item[0]) for item in kaggle_pkl]
kaggle_label = pd.DataFrame(kaggle_label, columns = ['emotion'])

In [89]:
kaggle_label_dummy = pd.get_dummies(kaggle_label, columns = kaggle_label)
kaggle_label_dummy = np.array(kaggle_label_dummy)

In [92]:
kaggle_label_target = np.argmax(np.array(kaggle_label_dummy, dtype=pd.Series),axis=1)
kaggle_label_text = kaggle_label.emotion.tolist()